#!/usr/bin/env bash

# install  nginx server
sudo apt-get update
sudo apt-get -y install nginx
sudo ufw allow 'Nginx HTTP'
echo "Hello World!" > /var/www/html/index.html
#echo "Hello World!" | tee /var/www/html/index.nginx-debian.html
sudo service nginx start
