#!/usr/bin/env bash
# Install and configure HAproxy on your load balancer server

ufw allow 1344
apt-get -y update
apt-get install -y haproxy

printf %s "
backend web-backend
        balance roundrobin
        option forwardfor
        server 54904-web-01 54.157.144.57:80 check
        server 54904-web-02 3.85.148.165:80 check
frontend proxynode
        bind *:80
        mode http
        default_backend web-backend
" >> /etc/haproxy/haproxy.cfg

sudo service haproxy restart
